### ISSUE TITLE
Homebrew thinks version is `64` rather than `0.22.2` on macOS

### ISSUE THREAD

**Issue by mcous** [withgraphite/homebrew-tap#7]
## Current behavior

```shell
❯ brew info withgraphite/tap/graphite
==> withgraphite/tap/graphite: stable 64
```

## Expected behavior

```shell
❯ brew info withgraphite/tap/graphite
==> withgraphite/tap/graphite: stable 0.22.2
```

## Notes

I believe this issue is caused by Homebrew's "autodetect version from URL" feature combined with the recent split between x64 and arm64

- Homebrew attempts to detect the version from the URL if `version` is not explicitly set ([source](https://docs.brew.sh/Formula-Cookbook#grab-the-url))
- https://github.com/withgraphite/homebrew-tap/commit/89679d6d8aa3606102f1b67701ef0343fff8a499 added `-x64` and `-arm64` suffixes to the URL

**Comment by goldjacobe** [comment]
Thanks! I'll put up a fix today

**Comment by goldjacobe** [comment]
Fixed now — anyone affected will need at most `brew uninstall graphite && brew untap withgraphite/tap && brew install withgraphite/tap/graphite` (the untapping may or may not be necessary, but willl ensure everything is up to date)

**Comment by mcous** [comment]
Thanks!

**Comment by avarun42** [comment]
> Fixed now — anyone affected will need at most `brew uninstall graphite && brew untap withgraphite/tap && brew install withgraphite/tap/graphite` (the untapping may or may not be necessary, but will ensure everything is up to date)

These instructions should probably be surfaced somewhere in the CLI if possible. I had to go digging to figure out why my CLI was not updating.
